### ISSUE TITLE
database connection issue

### ISSUE THREAD

**Issue by casakawa-jama** [CapstoneBitsPlease/JamaConnectBackend#44]
after successfully spinning up the backend i am getting a repeated error...

```
unable to open database file
Failed to connect to database.
```

this might be due to how my python environment is setup, i did have to muck around with the python imports to make it work for me.

honestly making this work just for me is very low priority. as long as ya'll demo is solid that is what matters.

**Comment by kt12359** [comment]
There was one path that got missed when we were going over and cleaning up all of the hard coded paths. We fixed it and that should solve this issue
