### ISSUE TITLE
error logs are too long

### ISSUE THREAD

**Issue by casakawa-jama** [CapstoneBitsPlease/JamaConnectBackend#45]
again, low priority...

since all my struggles of setting up this project i got myself into a use case where the error logs have become too large for the front-end.

 a size or time based rolling policy will fix this.

**Comment by CapstoneBitsPlease** [comment]
We actually just fixed this, it just hasn't been merged in yet but the functionality to select between two dates and get 20 logs at a time is functional. :)

**Comment by kt12359** [comment]
Added filter by date and get 20 items at a time for logging
