### ISSUE TITLE
routes are all running twice

### ISSUE THREAD

**Issue by casakawa-jama** [CapstoneBitsPlease/JamaConnectBackend#46]
the logs are reporting each route executing twice in rapid succession, is this something you are seeing as well? I suspect this might just be a weird effect of being in debug mode.

**Comment by kt12359** [comment]
Figured this out: when the root logger was retrieved apparently it was created with a handler automatically. I added a custom handler, so both were being used. I was able to fix the duplicate problem by removing any handlers at the time the initial logger was retrieved before adding our json handler.
